//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIM_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MIM_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewählte Icons zu einem Monitor zuweisen mit einem Klick auf gewünschten
        ///Monitor Button, wenn der Monitor schon zugewiesene Icons hat,
        ///gibt es Folgende Möglichkeiten:
        ///alle überschreiben; einzeln hinzufügen oder abbrechen ähnelt.
        /// </summary>
        public static string AF_Text {
            get {
                return ResourceManager.GetString("AF_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons Zuweisen ähnelt.
        /// </summary>
        public static string AF_Title {
            get {
                return ResourceManager.GetString("AF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIM ähnelt.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info Seite ähnelt.
        /// </summary>
        public static string FP_0_Title {
            get {
                return ResourceManager.GetString("FP_0_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler Resetten: 
        ///  In der ersten Zeile steht die Funktion dessen Methode, in den der Fehler passiert ist. 
        ///  Danach kommt der Fehlertext, meist mit fehler und Tipps. 
        ///  Zum Schluss ein Zeitstempel wann der Fehler passiert ist. 
        ///  Wenn in der Fehler hier resetet wurde, heißt es nicht das der Fehler weg ist,
        ///  dafür muss man die Nachricht lesen und handeln. ähnelt.
        /// </summary>
        public static string FP_00_Bo_FehlerResetBu2_TT {
            get {
                return ResourceManager.GetString("FP_00_Bo_FehlerResetBu2_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Fehlermeldung: ähnelt.
        /// </summary>
        public static string FP_00_Bo_FehlerTB00 {
            get {
                return ResourceManager.GetString("FP_00_Bo_FehlerTB00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier wird die letzte Fehlermeldung angezeigt. Behebe dieser und führe die gewünschte Aktion erneut durch. Fehler bei der Initialisierung oder beim Lesen der Daten, erfordert genaue Aufmerksamkeit. ähnelt.
        /// </summary>
        public static string FP_00_Bo_FehlerTB02 {
            get {
                return ResourceManager.GetString("FP_00_Bo_FehlerTB02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info Texte: ähnelt.
        /// </summary>
        public static string FP_02_Bo_InfoTB00 {
            get {
                return ResourceManager.GetString("FP_02_Bo_InfoTB00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Fehlermeldung: ähnelt.
        /// </summary>
        public static string FP_02_Bo_InfoTB01 {
            get {
                return ResourceManager.GetString("FP_02_Bo_InfoTB01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Statuse: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB00 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB01 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewählter M.: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB02 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inizialisiert: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB03 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modus: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB04 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler Neuladen: ähnelt.
        /// </summary>
        public static string FP_10_Bo_StatusTB05 {
            get {
                return ResourceManager.GetString("FP_10_Bo_StatusTB05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Status:
        ///  Hiermit werden Die Statuse angezeigt.
        ///    Donwload fertig: bei Grün Erfolgreich runtergeladen. 
        ///    Icon Pos Save: bei Grün Icon Positionen in extra Datei Gespeichert. 
        ///    Daten Gelesen: bei Grün wurden Informatonen aus Datei gelesen und lesbar gespeichert. ähnelt.
        /// </summary>
        public static string FP_12_Im_DOImage_TT {
            get {
                return ResourceManager.GetString("FP_12_Im_DOImage_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Status:
        ///  Hiermit werden Die Statuse angezeigt.
        ///    Donwload fertig: bei Grün Erfolgreich runtergeladen.
        ///    Monitor Configs Save: bei Grün alle Monitor Einstellungen in extra Config Datei Gespeichert.
        ///    Monitor Infos Save: bei Grün wurden Informatonen aus Datei gelesen und lesbar gespeichert. ähnelt.
        /// </summary>
        public static string FP_14_Im_MMImage_TT {
            get {
                return ResourceManager.GetString("FP_14_Im_MMImage_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Icon Manager ähnelt.
        /// </summary>
        public static string HP_0_Title {
            get {
                return ResourceManager.GetString("HP_0_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten neu Lesen:
        ///  Hiermit werden Monitordaten und Iconposition neu gelesen u. Gespeichert.
        ///  Gespeicherte Daten werden überschrieben also vorsichtig. ähnelt.
        /// </summary>
        public static string HP_00_Bu_btnReload_TT {
            get {
                return ResourceManager.GetString("HP_00_Bu_btnReload_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor 1:
        ///  Angezeigte Monitore haben ungefähr die Position der Windows Einstellung.
        ///  Dies dient zur Übersicht, falls Namen nicht bekannt.
        ///  Es werden auch: Namen, Aktivität und ob Primär dargestellt.
        ///  Mit dem Klick wählst du den Monitor aus, um damit weiter zu Arbeiten.
        ///  Monitorname Blau = Primer Monitor; Feld stark ausgegraut = Monitor inaktiv. ähnelt.
        /// </summary>
        public static string HP_00_Bu_Moni1_TT {
            get {
                return ResourceManager.GetString("HP_00_Bu_Moni1_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor 2:
        ///  Angezeigte Monitore haben ungefähr die Position der Windows Einstellung.
        ///  Dies dient zur Übersicht, falls Namen nicht bekannt.
        ///  Es werden auch: Namen, Aktivität und ob Primär dargestellt.
        ///  Mit dem Klick wählst du den Monitor aus, um damit weiter zu Arbeiten.
        ///  Monitorname Blau = Primer Monitor; Feld stark ausgegraut = Monitor inaktiv. ähnelt.
        /// </summary>
        public static string HP_00_Bu_Moni2_TT {
            get {
                return ResourceManager.GetString("HP_00_Bu_Moni2_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor 3:
        ///  Angezeigte Monitore haben ungefähr die Position der Windows Einstellung.
        ///  Dies dient zur Übersicht, falls Namen nicht bekannt.
        ///  Es werden auch: Namen, Aktivität und ob Primär dargestellt.
        ///  Mit dem Klick wählst du den Monitor aus, um damit weiter zu Arbeiten.
        ///  Monitorname Blau = Primer Monitor; Feld stark ausgegraut = Monitor inaktiv. ähnelt.
        /// </summary>
        public static string HP_00_Bu_Moni3_TT {
            get {
                return ResourceManager.GetString("HP_00_Bu_Moni3_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor 4:
        ///  Angezeigte Monitore haben ungefähr die Position der Windows Einstellung.
        ///  Dies dient zur Übersicht, falls Namen nicht bekannt.
        ///  Es werden auch: Namen, Aktivität und ob Primär dargestellt.
        ///  Mit dem Klick wählst du den Monitor aus, um damit weiter zu Arbeiten.
        ///  Monitorname Blau = Primer Monitor; Feld stark ausgegraut = Monitor inaktiv. ähnelt.
        /// </summary>
        public static string HP_00_Bu_Moni4_TT {
            get {
                return ResourceManager.GetString("HP_00_Bu_Moni4_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung erstellen:
        ///  es wird ein Icon auf den Desktopgespeichert der das aus
        ///  und Einschalten sowie das Verschieben der Icons ausführt,
        ///  dies ist dann von Monitor zu Monitor einzeln steuerbar. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelBu_btnCreateShortCut_TT {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelBu_btnCreateShortCut_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons verschieben:
        ///  Hier werden von den ausgewählten Monitor die Icons verschoben,
        ///  die zuvor in der Icon Auswahl gespeichert wurden. Beim zweiten Mal drücken mit dem
        ///  gleichen ausgewählten Monitor, werden die Icons wieder zurückverschoben. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelBu_btnIconsVerschieben_TT {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelBu_btnIconsVerschieben_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Schalter:
        ///  Hier kannst du den ausgewählten Monitor aktivieren oder deaktivieren,
        ///  dabei werden keine Icons verschoben jedoch werden Daten gelesen. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelBu_btnMonitorSwitch_TT {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelBu_btnMonitorSwitch_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon Auswahl:
        ///  Hiermit kannst du bestimmen welcher Icons verschoben werden sollen,
        ///  wenn ein Monitor deaktiviert wird. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelBu_btnSaveIconPos_TT {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelBu_btnSaveIconPos_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steuerpannel: ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelTB11 {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelTB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle zuerst ein Monitor aus indem du drauf klickst, die Auswahl bleibt so lange bestehen bis du das Fenster wechselst ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelTB12 {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelTB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn du über einen Button mit deiner Maus stehenbleibst, Erscheinen weitere Informationen dazu. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelTB13 {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelTB13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das erneute Lesen der Daten, nur mit vollen Setup durchführen, sonst gibt es Komplikation beim Wiederherstellen. ähnelt.
        /// </summary>
        public static string HP_01_Bo_PannelTB14 {
            get {
                return ResourceManager.GetString("HP_01_Bo_PannelTB14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitorinfos:
        ///  hier werden alle Monitorinfos vom ausgewählten Monitor angezeigt
        ///  diese werden bei der Initialisierung gelesen ähnelt.
        /// </summary>
        public static string HP_10_Bo_Infos_TT {
            get {
                return ResourceManager.GetString("HP_10_Bo_Infos_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Infos ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB01 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kurze Monitor ID: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB010 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor S.Nr: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB011 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeicherte Icons: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB012 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon Liste ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB013 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Name: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB02 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor Nummer: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB03 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auflösung: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB04 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB05 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiv Status: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB06 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primärstatus: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB07 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequenz: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB08 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Auflösung: ähnelt.
        /// </summary>
        public static string HP_10_Bo_InfosTB09 {
            get {
                return ResourceManager.GetString("HP_10_Bo_InfosTB09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons Zusweisen ähnelt.
        /// </summary>
        public static string ISP_0_Title {
            get {
                return ResourceManager.GetString("ISP_0_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string ISP_00_LV_btnListeSpeichern {
            get {
                return ResourceManager.GetString("ISP_00_LV_btnListeSpeichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons zuweisen:
        ///  Speichere alle gewählten Icons.
        ///  Wenn in Monitor Liste schon Icons existieren,
        ///  kannst du entweder alle überschreiben, einzeln hinzufügen oder abbrechen. ähnelt.
        /// </summary>
        public static string ISP_00_LV_btnListeSpeichern_TT {
            get {
                return ResourceManager.GetString("ISP_00_LV_btnListeSpeichern_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons ähnelt.
        /// </summary>
        public static string ISP_00_LV_Header1 {
            get {
                return ResourceManager.GetString("ISP_00_LV_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad ähnelt.
        /// </summary>
        public static string ISP_00_LV_Header2 {
            get {
                return ResourceManager.GetString("ISP_00_LV_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die InfoPage ähnelt.
        /// </summary>
        public static string ShellFunktionPage {
            get {
                return ResourceManager.GetString("ShellFunktionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open or close navigation ähnelt.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hauptseite ähnelt.
        /// </summary>
        public static string ShellHauptseitePage {
            get {
                return ResourceManager.GetString("ShellHauptseitePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IconSave ähnelt.
        /// </summary>
        public static string ShellIconSavePage {
            get {
                return ResourceManager.GetString("ShellIconSavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string SP_0_Title {
            get {
                return ResourceManager.GetString("SP_0_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string SP_1_ThemeRB1 {
            get {
                return ResourceManager.GetString("SP_1_ThemeRB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel-Blau ähnelt.
        /// </summary>
        public static string SP_1_ThemeRB2 {
            get {
                return ResourceManager.GetString("SP_1_ThemeRB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell-Blau ähnelt.
        /// </summary>
        public static string SP_1_ThemeRB3 {
            get {
                return ResourceManager.GetString("SP_1_ThemeRB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personalieseieren ähnelt.
        /// </summary>
        public static string SP_1_ThemeTB1 {
            get {
                return ResourceManager.GetString("SP_1_ThemeTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme wählen ähnelt.
        /// </summary>
        public static string SP_1_ThemeTB2 {
            get {
                return ResourceManager.GetString("SP_1_ThemeTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad ändern:
        ///  Wähle einen Pfad in dem alle Hintergrunddateien gespeichert werden soll.
        ///  In diesen Ordner werden die Icons verschoben oder config Dateien gespeichert.
        ///  Nach dem ändern wird die Initialisierung erneut durchgeführt und alle Daten gelöscht. ähnelt.
        /// </summary>
        public static string SP_2_ConfigBu2_btnSettingPath_TT {
            get {
                return ResourceManager.GetString("SP_2_ConfigBu2_btnSettingPath_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu Laden ähnelt.
        /// </summary>
        public static string SP_2_ConfigBu3_btnReload {
            get {
                return ResourceManager.GetString("SP_2_ConfigBu3_btnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu Laden:
        ///  Hier kannst du alle Monitordaten neu laden,
        ///  ohne darauf zu achten ob Monitore deaktiviert sind oder Icons verstaut.
        ///  Wichtigige Daten werden evtl Falsch Gespeichert wie z.B.:
        ///  Icon Position; Monitor Auflösung etc.
        ///  
        ///  Achte drauf was du tust! ähnelt.
        /// </summary>
        public static string SP_2_ConfigBu3_btnReload_TT {
            get {
                return ResourceManager.GetString("SP_2_ConfigBu3_btnReload_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string SP_2_ConfigBu3_btnReset {
            get {
                return ResourceManager.GetString("SP_2_ConfigBu3_btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset:
        ///  Hier werden alle Hintergrundsdaten gelöscht.
        ///  Anschließend wird die Initialisierung erneut durchgeführt.
        ///  Nur durchführen wenn du absolut sicher bist oder im Fehlerfall! ähnelt.
        /// </summary>
        public static string SP_2_ConfigBu3_btnReset_TT {
            get {
                return ResourceManager.GetString("SP_2_ConfigBu3_btnReset_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad für Hintergrund Daten: ähnelt.
        /// </summary>
        public static string SP_2_ConfigTB1 {
            get {
                return ResourceManager.GetString("SP_2_ConfigTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeicherte Einstellungen zurücksetzen oder Neu Laden: ähnelt.
        /// </summary>
        public static string SP_2_ConfigTB3 {
            get {
                return ResourceManager.GetString("SP_2_ConfigTB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über das Programm ähnelt.
        /// </summary>
        public static string SP_3_AboutTB1 {
            get {
                return ResourceManager.GetString("SP_3_AboutTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Programm ist zum Steuern von Monitoren und dessen Icons da. 
        ///Entwickelt von RyukYagami666, einen Programier Hobbyist. ähnelt.
        /// </summary>
        public static string SP_3_AboutTB3 {
            get {
                return ResourceManager.GetString("SP_3_AboutTB3", resourceCulture);
            }
        }
    }
}
