//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\%username%\\Documents\\DSM_Files")]
        public string pfadDeskOK {
            get {
                return ((string)(this["pfadDeskOK"]));
            }
            set {
                this["pfadDeskOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoMonitor1 {
            get {
                return ((string)(this["InfoMonitor1"]));
            }
            set {
                this["InfoMonitor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoMonitor2 {
            get {
                return ((string)(this["InfoMonitor2"]));
            }
            set {
                this["InfoMonitor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoMonitor3 {
            get {
                return ((string)(this["InfoMonitor3"]));
            }
            set {
                this["InfoMonitor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoMonitor4 {
            get {
                return ((string)(this["InfoMonitor4"]));
            }
            set {
                this["InfoMonitor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskIconPfadM1 {
            get {
                return ((string)(this["DeskIconPfadM1"]));
            }
            set {
                this["DeskIconPfadM1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskIconPfadM2 {
            get {
                return ((string)(this["DeskIconPfadM2"]));
            }
            set {
                this["DeskIconPfadM2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskIconPfadM3 {
            get {
                return ((string)(this["DeskIconPfadM3"]));
            }
            set {
                this["DeskIconPfadM3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskIconPfadM4 {
            get {
                return ((string)(this["DeskIconPfadM4"]));
            }
            set {
                this["DeskIconPfadM4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eUsername {
            get {
                return ((string)(this["eUsername"]));
            }
            set {
                this["eUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eDeskOkVers {
            get {
                return ((string)(this["eDeskOkVers"]));
            }
            set {
                this["eDeskOkVers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkDownloadReady {
            get {
                return ((bool)(this["eDeskOkDownloadReady"]));
            }
            set {
                this["eDeskOkDownloadReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkDownloadDone {
            get {
                return ((bool)(this["eDeskOkDownloadDone"]));
            }
            set {
                this["eDeskOkDownloadDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eDeskOkDownloadDate {
            get {
                return ((string)(this["eDeskOkDownloadDate"]));
            }
            set {
                this["eDeskOkDownloadDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkSavePosReady {
            get {
                return ((bool)(this["eDeskOkSavePosReady"]));
            }
            set {
                this["eDeskOkSavePosReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkSavePosDone {
            get {
                return ((bool)(this["eDeskOkSavePosDone"]));
            }
            set {
                this["eDeskOkSavePosDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eDeskOkSavePosDate {
            get {
                return ((string)(this["eDeskOkSavePosDate"]));
            }
            set {
                this["eDeskOkSavePosDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkDataReedReady {
            get {
                return ((bool)(this["eDeskOkDataReedReady"]));
            }
            set {
                this["eDeskOkDataReedReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eDeskOkDataReedDone {
            get {
                return ((bool)(this["eDeskOkDataReedDone"]));
            }
            set {
                this["eDeskOkDataReedDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eDeskOkDataReedDate {
            get {
                return ((string)(this["eDeskOkDataReedDate"]));
            }
            set {
                this["eDeskOkDataReedDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eDeskOkLastSave {
            get {
                return ((string)(this["eDeskOkLastSave"]));
            }
            set {
                this["eDeskOkLastSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskOkData {
            get {
                return ((string)(this["DeskOkData"]));
            }
            set {
                this["DeskOkData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskOkDataTrim {
            get {
                return ((string)(this["DeskOkDataTrim"]));
            }
            set {
                this["DeskOkDataTrim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeskIconPfadMTemp {
            get {
                return ((string)(this["DeskIconPfadMTemp"]));
            }
            set {
                this["DeskIconPfadMTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorVorhanden1 {
            get {
                return ((bool)(this["eMonitorVorhanden1"]));
            }
            set {
                this["eMonitorVorhanden1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorAktiv1 {
            get {
                return ((bool)(this["eMonitorAktiv1"]));
            }
            set {
                this["eMonitorAktiv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitorIconsZugewiesen1 {
            get {
                return ((string)(this["eMonitorIconsZugewiesen1"]));
            }
            set {
                this["eMonitorIconsZugewiesen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorIconsVerstaut1 {
            get {
                return ((bool)(this["eMonitorIconsVerstaut1"]));
            }
            set {
                this["eMonitorIconsVerstaut1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eMonitorIconsCount1 {
            get {
                return ((int)(this["eMonitorIconsCount1"]));
            }
            set {
                this["eMonitorIconsCount1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitor1 {
            get {
                return ((string)(this["eMonitor1"]));
            }
            set {
                this["eMonitor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorVorhanden2 {
            get {
                return ((bool)(this["eMonitorVorhanden2"]));
            }
            set {
                this["eMonitorVorhanden2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorAktiv2 {
            get {
                return ((bool)(this["eMonitorAktiv2"]));
            }
            set {
                this["eMonitorAktiv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitorIconsZugewiesen2 {
            get {
                return ((string)(this["eMonitorIconsZugewiesen2"]));
            }
            set {
                this["eMonitorIconsZugewiesen2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorIconsVerstaut2 {
            get {
                return ((bool)(this["eMonitorIconsVerstaut2"]));
            }
            set {
                this["eMonitorIconsVerstaut2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eMonitorIconsCount2 {
            get {
                return ((int)(this["eMonitorIconsCount2"]));
            }
            set {
                this["eMonitorIconsCount2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitor2 {
            get {
                return ((string)(this["eMonitor2"]));
            }
            set {
                this["eMonitor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorVorhanden3 {
            get {
                return ((bool)(this["eMonitorVorhanden3"]));
            }
            set {
                this["eMonitorVorhanden3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorAktiv3 {
            get {
                return ((bool)(this["eMonitorAktiv3"]));
            }
            set {
                this["eMonitorAktiv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitorIconsZugewiesen3 {
            get {
                return ((string)(this["eMonitorIconsZugewiesen3"]));
            }
            set {
                this["eMonitorIconsZugewiesen3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorIconsVerstaut3 {
            get {
                return ((bool)(this["eMonitorIconsVerstaut3"]));
            }
            set {
                this["eMonitorIconsVerstaut3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eMonitorIconsCount3 {
            get {
                return ((int)(this["eMonitorIconsCount3"]));
            }
            set {
                this["eMonitorIconsCount3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitor3 {
            get {
                return ((string)(this["eMonitor3"]));
            }
            set {
                this["eMonitor3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorVorhanden4 {
            get {
                return ((bool)(this["eMonitorVorhanden4"]));
            }
            set {
                this["eMonitorVorhanden4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorAktiv4 {
            get {
                return ((bool)(this["eMonitorAktiv4"]));
            }
            set {
                this["eMonitorAktiv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitorIconsZugewiesen4 {
            get {
                return ((string)(this["eMonitorIconsZugewiesen4"]));
            }
            set {
                this["eMonitorIconsZugewiesen4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool eMonitorIconsVerstaut4 {
            get {
                return ((bool)(this["eMonitorIconsVerstaut4"]));
            }
            set {
                this["eMonitorIconsVerstaut4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eMonitorIconsCount4 {
            get {
                return ((int)(this["eMonitorIconsCount4"]));
            }
            set {
                this["eMonitorIconsCount4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eMonitor4 {
            get {
                return ((string)(this["eMonitor4"]));
            }
            set {
                this["eMonitor4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int eMonitorIconsCountTemp {
            get {
                return ((int)(this["eMonitorIconsCountTemp"]));
            }
            set {
                this["eMonitorIconsCountTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b5 {
            get {
                return ((string)(this["b5"]));
            }
            set {
                this["b5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b6 {
            get {
                return ((string)(this["b6"]));
            }
            set {
                this["b6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b7 {
            get {
                return ((string)(this["b7"]));
            }
            set {
                this["b7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b8 {
            get {
                return ((string)(this["b8"]));
            }
            set {
                this["b8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string b89 {
            get {
                return ((string)(this["b89"]));
            }
            set {
                this["b89"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c1 {
            get {
                return ((string)(this["c1"]));
            }
            set {
                this["c1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c2 {
            get {
                return ((string)(this["c2"]));
            }
            set {
                this["c2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c3 {
            get {
                return ((string)(this["c3"]));
            }
            set {
                this["c3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c4 {
            get {
                return ((string)(this["c4"]));
            }
            set {
                this["c4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c5 {
            get {
                return ((string)(this["c5"]));
            }
            set {
                this["c5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c6 {
            get {
                return ((string)(this["c6"]));
            }
            set {
                this["c6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c7 {
            get {
                return ((string)(this["c7"]));
            }
            set {
                this["c7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c8 {
            get {
                return ((string)(this["c8"]));
            }
            set {
                this["c8"] = value;
            }
        }
    }
}
